name: hnews
version: '0.0.0.1'
synopsis: See README for more info
description: See README for more info
author: Paul
maintainer: Paul <paul.dhubert@pm.me>
copyright: 2021 Paul
license: MIT
github: pauldub/hnews.git

language: GHC2021

dependencies:
  - base >=4.14.1.0
  - text

default-extensions:
  - OverloadedStrings
  - TypeFamilies
  - RecordWildCards
  - OverloadedRecordDot

library:
  source-dirs: src
  exposed-modules:
  - HNews
  - HNews.Feed
  - HNews.Feed.RSS
  - HNews.Feed.GitHub
  - HNews.Entry
  dependencies:
    - feed
    - github
    - mtl

executables:
  hnews:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hnews
tests:
  hnews-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hnews
    - tasty
    - tasty-hunit
    - github
tested-with: ghc ==8.10.5
